name: CMake

on:
  push:
    branches:
      - master

env:
  CC: /usr/bin/gcc-9
  CXX: /usr/bin/g++-9

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Install pip3 for x64
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install GNU compiler
      run: sudo apt-get install -y gcc-9 g++-9

    - name: Install Conan
      run: pip install conan

    - name: Build
      shell: bash
      run: ./build.sh
